### ISSUE TITLE
[Proposal] refaktor komend

### ISSUE THREAD

**Issue by gorzalczany** [Deseteral/lebkuchen-fm#120]
### Stan obecny
Jest kilka powodów dla których przydałby się refaktor tego jak wyglądają komendy:
- jest ich coraz więcej
- są coraz bardziej skomplikowane
- help staje się nieczytelny
  - jego długość zaczyna przekraczać limity API Slackowego

Dla przykładu w PRze https://github.com/Deseteral/lebkuchen-fm/pull/119 dodajemy komendę tag.
Ma ona zaproponowaną już dość fajną semantykę `tag-*`, dzięki której wszystkie komendy obsługujące tę funkcjonalność są niejako zgrupowane. Jej przeciwieństwem jest obsługa `x-sound`, do której wykorzystujemy komendy `x`, `listx` oraz `addx`. Są one rozrzucone po dorzuceniu semantyki `tag-*` nie będzie między nimi żadnej analogii.
Oprócz tego `addx` za chwilę wyleci na rzecz formularza webowego do uploadu plików.

### Propozycja:
- odnośnie `x`
  - rename `x` na `sound` z aliasem `x`
  - rename `listx` na `sound-list` z aliasem `x-list`
- odnośnie `s`
  - rename `s` na `song-search` z aliasem `s`
  - rename `q` na `song-queue` z aliasem `q`
- odnośnie `help`
  - zgrupowanie helpów / grupowanie komend na backendzie (spory refaktor?)
  - `/fm help` wyświetlałby tylko uproszczone info:
```
`/fm help` - wyświetla tą wiadomość

Oprócz tego dostępne są następujące komendy:
- sound [x]
- song [s]
- skip
- tag [t] - zarządzanie systemem tagowania dźwięków

Szczegółowe wykorzystanie komend:
  `/fm help [command]`
  `/fm [command]-help`
```
  - komendy miałyby swoje szczegółowe helpy
  - odpalenie komendy z samą nazwą grupującą mogłoby wyświetlałoby helpa
  - na przkładzie komendy [tag]
    - `/fm tag` - wyświetla szczegółowego helpa komendy tag
    - `/fm tag-help`  - wyświetla szczegółowego helpa komendy tag
    - `/fm tag-list` - wyświetla listę tagów
    - `/fm tag-add xyz|abc`
    - itd
 
### Inspiracja:
Wzorowałbym się np tym jak wyświetlane jest `brew help` lub inne polecenia znane z terminala.
Może ktoś ma lepszy przykład.

**Comment by Deseteral** [comment]
Okej, mi się podoba. Kilka rzeczy:

Proponuje dodatkowo zrobić rename `add` na `song-add` (bez aliasu). Dołączy wtedy do grupy `song-search` i `song-queue`.

---

> rename `listx` na `sound-list` z aliasem `x-list`

`x-list` nie jest dużo krótszy od `sound-list`, przez co nie spełnia funkcji aliasu. IMO zróbmy rename, ale bez aliasu.

---

Z komend o których nie pisałeś wyłania mi się jeszcze grupa, która kontroluje odtwarzanie, a więc może:
- `playback-pause`
- `playback-resume`
- `playback-skip`
- `playback-speed`
- `playback-volume`

Brzmi to logicznie, martwi mnie natomiast długość tych komend (szczególnie skip). Może jakieś propozycje prefixu innego niż `playback-*`.

---

Warto pomyśleć jak będziemy z tym systemem pracować w przyszłości.

To co mamy na radarze to:
- dodawanie na początek kolejki (#80, #87)
- wyświetlanie kolejki na Slacku (#116, bez PRa jeszcze)

Dodatkowo, mamy jeszcze komendę `random`, który działa bez argumentów, a także z liczbą (np. `random 3`). Chcieliśmy zaimplementować losowe dodawanie utworu na query z historii. Czy tutaj rodzi się jakaś grupa?

Czy mamy jakiś pomysł na to jak zaopiekować się takimi komendami?

---

Na koniec absolutna pierdoła. Czy nie lepiej zamiast `/fm tag-help` mieć komendę help, która łyka argument z nazwą kolejki (`/fm help tag`)?

**Comment by gorzalczany** [comment]
`playback-*` podoba mi się bardzo, a aliasami zostawiłbym obecne nazewnictwo
- zyskamy porządek
- nie zmienimy przyzwyczajeni i szybkości wpisywania

`tag-help` można zignorować, składnia `help [command]` jest fajna.
Jeżeli parser komendy rzuci błędem bez wyjaśnienia to możemy wtedy wyświetlać zawartość `help [command]`

`random`
- rename na `song-random` z aliasem `random`?
-umożliwiłoby to dorzucenie niekonfliktującego `sound-random` jeżeli ktoś by poczuł taką potrzebę ;)

"Z radaru"
mi się podobało korzystanie z "opcji", czyli:
- song-search --as-next "xyz"
- song-queue --as-next "xyz"
ale nie przeszło przy wcześniejszych review ;)

**Comment by Deseteral** [comment]
A nie wydaje Ci się że jak robimy rename i zostawiamy alias taki jak był, to tak jakbyśmy nie robili rename? :D

**Comment by gorzalczany** [comment]
I tak i nie, porządkujemy je wspólnym prefixem dla mnie samo to jest w sobie korzyścią :)

**Comment by gorzalczany** [comment]
Zamykamy?

**Comment by Deseteral** [comment]
Closed by #161
