### ISSUE TITLE
Quick search input on dashboard

### ISSUE THREAD

**Issue by Deseteral** [Deseteral/lebkuchen-fm#20]
AC:
- when user presses `ctrl+f` (or `cmd+f` on Mac) a search form pops up
- when user enters query into the search form and presses `enter` the player queues first search result from YouTube for given query

**Comment by duffbuster** [comment]
@Deseteral do you care if this is styled? Also, is there any search functionality built in already?

**Comment by Deseteral** [comment]
You can leave styling to me :)
There is `/fm search` command - you can see how it is implemented [here](https://github.com/Deseteral/lebkuchen-fm/blob/master/server/commands/SearchCommand.ts) 😄
